{{- if .Values.foo.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "http-echo.fullname" . }}-foo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
    app.kubernetes.io/component: foo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "http-echo.fullname" . }}-foo
  minReplicas: {{ .Values.foo.hpa.minReplicas }}
  maxReplicas: {{ .Values.foo.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.foo.hpa.targetCPUUtilizationPercentage }}
{{- end }}
