{{- if .Values.bar.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "http-echo.fullname" . }}-bar
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
    app.kubernetes.io/component: bar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "http-echo.fullname" . }}-bar
  minReplicas: {{ .Values.bar.hpa.minReplicas }}
  maxReplicas: {{ .Values.bar.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bar.hpa.targetCPUUtilizationPercentage }}
{{- end }}
