{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "http-echo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
{{- end }}
