apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo.fullname" . }}-foo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
    app.kubernetes.io/component: foo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "http-echo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: foo
